#!/bin/bash

# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "No arguments provided"
    exit 1
fi

# Create a new .cpp file with the name provided as the argument
filename="$1.cpp"

# Write the desired content into the new file
echo '#include <iostream>

using namespace std;

int main() {

}' > "$filename"

# Open the new file with neovim
nvim "$filename"
