#!/bin/bash

# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "No arguments provided"
    exit 1
fi

# Create a new .cpp file with the name provided as the argument
filename="$1.cpp"

# Write the desired content into the new file
echo '#include <bits/stdc++.h>

using namespace std;

int main() {
    ios::sync_with_stdio(0);
    cin.tie(0);

}' > "$filename"

# Open the new file with neovim
nvim "$filename"
